export const CATEGORIA_REPOSITORY = 'CATEGORIA_REPOSITORY';
export const CURSO_REPOSITORY = 'CURSO_REPOSITORY';
export const PLANETA_REPOSITORY = 'PLANETA_REPOSITORY';
export const GALAXIA_REPOSITORY = 'GALAXIA_REPOSITORY';
export const IDIOMA_REPOSITORY = 'IDIOMA_REPOSITORY';
export const LANDING_PAGE_REPOSITORY = 'LANDING_PAGE_REPOSITORY';
export const PROFESOR_REPOSITORY = 'PROFESOR_REPOSITORY';
