export const PROFESOR_FACTORY = 'PROFESOR_FACTORY';
export const PROFESOR_DTO_FACTORY = 'PROFESOR_DTO_FACTORY';

export const CATEGORIA_FACTORY = 'CATEGORIA_FACTORY';
export const CATEGORIA_DTO_FACTORY = 'CATEGORIA_DTO_FACTORY';

export const GALAXIA_FACTORY = 'GALAXIA_FACTORY';
export const GALAXIA_DTO_FACTORY = 'GALAXIA_DTO_FACTORY';

export const IDIOMA_FACTORY = 'IDIOMA_FACTORY';
export const IDIOMA_DTO_FACTORY = 'IDIOMA_DTO_FACTORY';

export const CURSO_FACTORY = 'CURSO_FACTORY';
export const CURSO_DTO_FACTORY = 'CURSO_DTO_FACTORY';

export const ESTANDAR_FACTORY = 'ESTANDAR_FACTORY';
export const ESTANDAR_DTO_FACTORY = 'ESTANDAR_DTO_FACTORY';

export const LANDING_PAGE_FACTORY = 'LANDING_PAGE_FACTORY';
export const LANDING_PAGE_DTO_FACTORY = 'LANDING_PAGE_DTO_FACTORY';

export const PLANETA_FACTORY = 'PLANETA_FACTORY';
export const PLANETA_DTO_FACTORY = 'PLANETA_DTO_FACTORY';
